# Generated by Django 2.1.7 on 2021-04-17 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AutoProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dicom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patientid', models.CharField(blank=True, max_length=50, null=True, verbose_name='patientid')),
                ('patientname', models.CharField(blank=True, max_length=50, null=True, verbose_name='id')),
                ('studyinstanceuid', models.CharField(blank=True, max_length=120, null=True, verbose_name='数据uid')),
                ('diseases', models.CharField(blank=True, max_length=20, null=True, verbose_name='病种类型')),
                ('slicenumber', models.CharField(blank=True, max_length=6, null=True, verbose_name='肺炎层厚')),
                ('imagecount', models.CharField(blank=True, max_length=5, null=True, verbose_name='张数')),
                ('vote', models.CharField(blank=True, max_length=800, null=True, verbose_name='挂载')),
                ('graphql', models.TextField(blank=True, max_length=5000, null=True, verbose_name='graphql')),
                ('fileid', models.CharField(blank=True, max_length=5, null=True, verbose_name='文件ID')),
                ('diagnosis', models.CharField(blank=True, max_length=200, null=True, verbose_name='诊断结果')),
                ('predictor', models.CharField(blank=True, max_length=5, null=True, verbose_name='模型')),
                ('type', models.CharField(blank=True, max_length=10, null=True, verbose_name='类型')),
                ('route', models.CharField(blank=True, max_length=100, null=True, verbose_name='路径')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('stressstatus', models.CharField(blank=True, max_length=5, null=True, verbose_name='性能状态')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'dicom数据表',
                'verbose_name_plural': 'dicom数据表',
                'db_table': 'dicom',
            },
        ),
        migrations.CreateModel(
            name='dicom_base',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=500, null=True, verbose_name='内容')),
                ('type', models.CharField(blank=True, max_length=10, null=True, verbose_name='类型')),
                ('select_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='查询类型')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('other', models.CharField(blank=True, max_length=10, null=True, verbose_name='其他')),
                ('predictor', models.CharField(blank=True, max_length=25, null=True, verbose_name='其他')),
                ('status', models.BooleanField(default=True, verbose_name='0是关闭，1是启用')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '基础数据表',
                'verbose_name_plural': '基础数据表',
                'db_table': 'dicom_base',
            },
        ),
        migrations.CreateModel(
            name='dicom_group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='组名')),
                ('type', models.CharField(blank=True, max_length=10, null=True, verbose_name='类型')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
            ],
            options={
                'verbose_name': 'dicom组表',
                'verbose_name_plural': 'dicom组表',
                'db_table': 'dicom_group',
            },
        ),
        migrations.CreateModel(
            name='dicom_group_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dicom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AutoDicom.dicom', verbose_name='id')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AutoDicom.dicom_group', verbose_name='id')),
            ],
            options={
                'verbose_name': 'dicom组表',
                'verbose_name_plural': 'dicom组表',
                'db_table': 'dicom_group_detail',
            },
        ),
        migrations.CreateModel(
            name='duration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, max_length=20, null=True, verbose_name='版本')),
                ('server', models.CharField(blank=True, max_length=20, null=True, verbose_name='服务器ip')),
                ('port', models.CharField(blank=True, max_length=10, null=True, verbose_name='服务器端口号')),
                ('aet', models.CharField(blank=True, max_length=20, null=True, verbose_name='aet')),
                ('patientid', models.CharField(blank=True, max_length=50, null=True, verbose_name='patientid')),
                ('patientname', models.CharField(blank=True, max_length=50, null=True, verbose_name='patientname')),
                ('dicom', models.CharField(blank=True, max_length=100, null=True, verbose_name='dicom数据')),
                ('group', models.CharField(blank=True, max_length=200, null=True, verbose_name='组信息')),
                ('sendcount', models.IntegerField(blank=True, null=True, verbose_name='共计发送')),
                ('start_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='开始时间')),
                ('end_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='结束时间')),
                ('sleepcount', models.CharField(blank=True, max_length=20, null=True, verbose_name='睡眠张数')),
                ('sleeptime', models.CharField(blank=True, max_length=20, null=True, verbose_name='睡眠时间')),
                ('series', models.BooleanField(default=True, verbose_name='series')),
                ('sendstatus', models.BooleanField(default=True, verbose_name='发送状态')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='发送类型')),
                ('dds', models.CharField(blank=True, max_length=20, null=True, verbose_name='dds 服务')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('Host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AutoProject.Server', verbose_name='Host')),
            ],
            options={
                'verbose_name': '持续化配置',
                'verbose_name_plural': '持续化配置',
                'db_table': 'duration',
            },
        ),
        migrations.CreateModel(
            name='duration_record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patientid', models.CharField(blank=True, max_length=80, null=True, verbose_name='patientid')),
                ('patientname', models.CharField(blank=True, max_length=50, null=True, verbose_name='id')),
                ('accessionnumber', models.CharField(blank=True, max_length=80, null=True, verbose_name='accessionnumber')),
                ('studyinstanceuid', models.CharField(blank=True, max_length=200, null=True, verbose_name='数据uid')),
                ('studyolduid', models.CharField(blank=True, max_length=200, null=True, verbose_name='影像张数验证')),
                ('imagecount', models.CharField(blank=True, max_length=50, null=True, verbose_name='发送影像张数')),
                ('imagecount_server', models.CharField(blank=True, max_length=50, null=True, verbose_name='接收影像张数')),
                ('aistatus', models.CharField(blank=True, max_length=10, null=True, verbose_name='AI预测结果')),
                ('diagnosis', models.TextField(blank=True, max_length=500, null=True, verbose_name='诊断结果')),
                ('sendserver', models.CharField(blank=True, max_length=20, null=True, verbose_name='发送服务')),
                ('sendtime', models.CharField(blank=True, max_length=20, null=True, verbose_name='发送开始时间')),
                ('starttime', models.CharField(blank=True, max_length=20, null=True, verbose_name='预测时间')),
                ('endtime', models.CharField(blank=True, max_length=20, null=True, verbose_name='发送结束时间')),
                ('jobtime', models.CharField(blank=True, max_length=20, null=True, verbose_name='job时间')),
                ('error', models.TextField(blank=True, max_length=3000, null=True, verbose_name='error信息')),
                ('model', models.CharField(blank=True, max_length=30, null=True, verbose_name='模型')),
                ('time', models.CharField(blank=True, max_length=20, null=True, verbose_name='发送时间')),
                ('duration_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='duration_id')),
                ('diseases', models.CharField(blank=True, max_length=20, null=True, verbose_name='预测类型')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '持续化测试记录表',
                'verbose_name_plural': '持续化测试记录表',
                'db_table': 'duration_record',
            },
        ),
    ]
