# Generated by Django 2.1.7 on 2021-03-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoDicom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duration',
            name='type',
            field=models.IntegerField(blank=True, null=True, verbose_name='type 0：匿名化 1：持续化 2：性能'),
        ),
    ]
