# Generated by Django 2.1.7 on 2021-03-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoDicom', '0002_duration_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duration',
            name='anonymous',
        ),
        migrations.AlterField(
            model_name='duration',
            name='series',
            field=models.BooleanField(default=True, verbose_name='series'),
        ),
        migrations.AlterField(
            model_name='duration',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='type'),
        ),
    ]
