# Generated by Django 2.1.7 on 2021-03-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoDicom', '0003_auto_20210324_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='duration',
            name='start_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='duration',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='发送类型'),
        ),
    ]
