# Generated by Django 2.1.7 on 2021-03-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoDicom', '0004_auto_20210324_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='duration',
            name='version',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='版本'),
        ),
    ]
