# Generated by Django 2.1.7 on 2021-03-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoDicom', '0006_auto_20210325_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='duration_record',
            name='error',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='job时间'),
        ),
        migrations.AddField(
            model_name='duration_record',
            name='jobtime',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='job时间'),
        ),
        migrations.AddField(
            model_name='duration_record',
            name='model',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='模型'),
        ),
    ]
