# Generated by Django 2.1.7 on 2021-04-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoDicom', '0008_auto_20210329_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration_record',
            name='duration_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='duration_id'),
        ),
    ]
