# Generated by Django 2.1.7 on 2021-04-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoDicom', '0009_auto_20210407_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration_record',
            name='error',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='error信息'),
        ),
    ]
