# Generated by Django 2.1.7 on 2021-04-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoDicom', '0010_auto_20210409_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration_record',
            name='diagnosis',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='诊断结果'),
        ),
    ]
