# Generated by Django 2.1.7 on 2021-04-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoDicom', '0012_auto_20210412_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='duration',
            name='group',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='组信息'),
        ),
    ]
