# Generated by Django 2.1.7 on 2020-11-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='interface',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interfacename', models.CharField(blank=True, max_length=10, null=True, verbose_name='接口名')),
                ('json', models.CharField(blank=True, max_length=500, null=True, verbose_name='json')),
                ('type', models.CharField(blank=True, max_length=10, null=True, verbose_name='类型')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
            ],
            options={
                'verbose_name': 'Interface表',
                'verbose_name_plural': 'Interface表',
                'db_table': 'interface',
            },
        ),
    ]
