# Generated by Django 2.1.7 on 2020-06-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stressrecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('testversion', models.CharField(blank=True, max_length=500, null=True, verbose_name='测试版本')),
                ('loadserver', models.CharField(blank=True, max_length=1, null=True, verbose_name='测试环境')),
                ('testdata', models.CharField(blank=True, max_length=100, null=True, verbose_name='测试数据')),
                ('testcount', models.CharField(blank=True, max_length=50, null=True, verbose_name='执行次数')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '性能测试记录表',
                'verbose_name_plural': '性能测试记录表',
                'db_table': 'stressrecord',
            },
        ),
    ]
