# Generated by Django 2.1.7 on 2020-11-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dicomroute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dicomid', models.CharField(blank=True, max_length=10, null=True, verbose_name='关联dicom')),
                ('route', models.CharField(blank=True, max_length=100, null=True, verbose_name='路径')),
            ],
            options={
                'verbose_name': 'dicom路径',
                'verbose_name_plural': 'dicom路径',
                'db_table': 'dicomroute',
            },
        ),
        migrations.AlterModelOptions(
            name='dicomdata',
            options={'verbose_name': 'dicom数据表', 'verbose_name_plural': 'dicom数据表'},
        ),
        migrations.AddField(
            model_name='dicomdata',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='诊断结果'),
        ),
        migrations.AddField(
            model_name='dicomdata',
            name='predictor',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='预测类型'),
        ),
        migrations.AddField(
            model_name='stress_record',
            name='dicom_send',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='dicom 发送'),
        ),
        migrations.AddField(
            model_name='stress_record',
            name='duration',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='持续时间'),
        ),
        migrations.AddField(
            model_name='stress_record',
            name='loop_count',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='循环次数'),
        ),
        migrations.AddField(
            model_name='stress_record',
            name='projectname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='项目名称'),
        ),
        migrations.AddField(
            model_name='stress_record',
            name='ramp',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='ramp up time'),
        ),
        migrations.AddField(
            model_name='stress_record',
            name='start_delay',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='启动延时 秒'),
        ),
        migrations.AddField(
            model_name='stress_record',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='stress_record',
            name='synchroniz',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='并发vu'),
        ),
        migrations.AddField(
            model_name='stress_record',
            name='thread',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='线程数'),
        ),
    ]
