# Generated by Django 2.1.7 on 2020-08-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='duration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('server', models.CharField(blank=True, max_length=20, null=True, verbose_name='服务器ip')),
                ('keyword', models.CharField(blank=True, max_length=20, null=True, verbose_name='匿名名称')),
                ('dicom', models.CharField(blank=True, max_length=20, null=True, verbose_name='dicom数据')),
                ('time', models.CharField(blank=True, max_length=20, null=True, verbose_name='发送时间')),
                ('sendstatus', models.BooleanField(default=True, verbose_name='发送状态')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '持续化配置',
                'verbose_name_plural': '持续化配置',
                'db_table': 'duration',
            },
        ),
        migrations.CreateModel(
            name='stress_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patientid', models.CharField(blank=True, max_length=50, null=True, verbose_name='patientid')),
                ('studyinstanceuid', models.CharField(blank=True, max_length=100, null=True, verbose_name='数据uid')),
                ('diseases', models.CharField(blank=True, max_length=20, null=True, verbose_name='预测类型')),
                ('automatic', models.CharField(blank=True, max_length=5, null=True, verbose_name='自动或手动预测')),
                ('vote', models.CharField(blank=True, max_length=500, null=True, verbose_name='挂载')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '测试数据表',
                'verbose_name_plural': '测试数据表',
                'db_table': 'stress_data',
            },
        ),
        migrations.RemoveField(
            model_name='stress_record',
            name='block',
        ),
        migrations.AddField(
            model_name='duration_record',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='测试'),
        ),
        migrations.AddField(
            model_name='stress_record',
            name='end_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='压测结束时间'),
        ),
        migrations.AddField(
            model_name='stress_record',
            name='start_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='压测开始时间'),
        ),
        migrations.AlterField(
            model_name='base_data',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='base_data',
            name='select_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='查询类型'),
        ),
        migrations.AlterField(
            model_name='base_data',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='duration_record',
            name='accessionnumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='accessionnumber'),
        ),
        migrations.AlterField(
            model_name='duration_record',
            name='aistatus',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='测试数据'),
        ),
        migrations.AlterField(
            model_name='duration_record',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='测试数据'),
        ),
        migrations.AlterField(
            model_name='duration_record',
            name='imagecount',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='测试'),
        ),
        migrations.AlterField(
            model_name='duration_record',
            name='imagecount_server',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='测试'),
        ),
        migrations.AlterField(
            model_name='duration_record',
            name='patientid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='patientid'),
        ),
        migrations.AlterField(
            model_name='duration_record',
            name='sendserver',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='发送服务'),
        ),
        migrations.AlterField(
            model_name='duration_record',
            name='studyinstanceuid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='数据uid'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='stress_detail_record',
            name='report',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='诊断报告'),
        ),
        migrations.AlterField(
            model_name='stress_record',
            name='loop_time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='执行时间'),
        ),
        migrations.AlterField(
            model_name='stress_record',
            name='testdata',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='测试数据'),
        ),
    ]
