# Generated by Django 2.1.7 on 2020-11-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stress_record',
            name='dicom_send',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='dicom 发送'),
        ),
        migrations.AddField(
            model_name='stress_record',
            name='duration',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='持续时间'),
        ),
        migrations.AddField(
            model_name='stress_record',
            name='loop_count',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='循环次数'),
        ),
        migrations.AddField(
            model_name='stress_record',
            name='projectname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='项目名称'),
        ),
        migrations.AddField(
            model_name='stress_record',
            name='ramp',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='ramp up time'),
        ),
        migrations.AddField(
            model_name='stress_record',
            name='start_delay',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='启动延时 秒'),
        ),
        migrations.AddField(
            model_name='stress_record',
            name='synchroniz',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='并发vu'),
        ),
        migrations.AddField(
            model_name='stress_record',
            name='thread',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='线程数'),
        ),
    ]
