# Generated by Django 2.1.7 on 2020-11-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0002_auto_20201127_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_data',
            name='predictor',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='其他'),
        )
    ]
