# Generated by Django 2.1.7 on 2020-10-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0002_auto_20201029_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='duration',
            name='series',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='series'),
        ),
    ]
