# Generated by Django 2.1.7 on 2020-06-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0002_stressrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='duration_record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patientid', models.CharField(blank=True, max_length=50, null=True, verbose_name='id')),
                ('accessionnumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='测试')),
                ('studyinstanceuid', models.CharField(blank=True, max_length=80, null=True, verbose_name='数据uid')),
                ('imagecount', models.CharField(blank=True, max_length=20, null=True, verbose_name='测试')),
                ('imagecount_server', models.CharField(blank=True, max_length=40, null=True, verbose_name='测试')),
                ('aistatus', models.CharField(blank=True, max_length=30, null=True, verbose_name='测试数据')),
                ('diagnosis', models.CharField(blank=True, max_length=30, null=True, verbose_name='测试数据')),
                ('sendserver', models.CharField(blank=True, max_length=10, null=True, verbose_name='发送服务')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '持续化测试记录表',
                'verbose_name_plural': '持续化测试记录表',
                'db_table': 'duration_record',
            },
        ),
        migrations.CreateModel(
            name='stress_record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, max_length=20, null=True, verbose_name='测试版本')),
                ('loadserver', models.CharField(blank=True, max_length=40, null=True, verbose_name='测试环境')),
                ('testdata', models.CharField(blank=True, max_length=30, null=True, verbose_name='测试数据')),
                ('block', models.CharField(blank=True, max_length=5, null=True, verbose_name='手动&自动预测')),
                ('loop_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='执行次数')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '性能测试记录表',
                'verbose_name_plural': '性能测试记录表',
                'db_table': 'stress_record',
            },
        ),
        migrations.DeleteModel(
            name='stressrecord',
        ),
    ]
