# Generated by Django 2.1.7 on 2020-07-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0002_auto_20200717_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stress_detail_record',
            name='report',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='诊断报告'),
        ),
        migrations.AlterField(
            model_name='stress_record',
            name='testdata',
            field=models.TextField(blank=True, max_length=30, null=True, verbose_name='测试数据'),
        ),
    ]
