# Generated by Django 2.1.7 on 2020-08-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0002_auto_20200825_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='duration',
            name='port',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='服务器端口号'),
        ),
    ]
