# Generated by Django 2.1.7 on 2020-12-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0002_auto_20201204_1409'),
    ]

    operations = [

        migrations.CreateModel(
            name='dictionary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, max_length=50, null=True, verbose_name='key')),
                ('value', models.CharField(blank=True, max_length=2500, null=True, verbose_name='value')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='说明')),
                ('type', models.CharField(blank=True, max_length=10, null=True, verbose_name='类型')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
            ],
            options={
                'verbose_name': 'dictionary表',
                'verbose_name_plural': 'dictionary表',
                'db_table': 'dictionary',
            },
        ),
        migrations.AlterField(
            model_name='interface',
            name='interfacename',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='接口名'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='json',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='json'),
        ),
    ]
