# Generated by Django 2.1.7 on 2020-11-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0002_auto_20201113_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='stress_data',
            name='predictor',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='预测类型'),
        ),
    ]
