# Generated by Django 2.1.7 on 2020-07-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0003_auto_20200718_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stress_record',
            name='testdata',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='测试数据'),
        ),
    ]
