# Generated by Django 2.1.7 on 2020-12-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0003_auto_20201127_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicom_route',
            name='dicomid',
        ),
        migrations.AddField(
            model_name='dicom_route',
            name='study_uid',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='关联dicom'),
        ),
        migrations.AlterField(
            model_name='dicom_route',
            name='route',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='路径'),
        ),
    ]
