# Generated by Django 2.1.7 on 2020-12-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0003_auto_20201210_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='dds_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostID', models.CharField(blank=True, max_length=30, null=True, verbose_name='hostID')),
                ('patientID', models.CharField(blank=True, max_length=30, null=True, verbose_name='patientID')),
                ('accesionNumber', models.CharField(blank=True, max_length=30, null=True, verbose_name='accessionNumber')),
                ('studyInstanceUID', models.CharField(blank=True, max_length=30, null=True, verbose_name='studyInstanceUID')),
                ('pacsImageCount', models.IntegerField(blank=True, null=True, verbose_name='pacsImageCount')),
                ('pacsImageInsertionTime', models.DateTimeField(auto_now_add=True, verbose_name='pacsImageInsertionTime')),
                ('orthancImageCount', models.IntegerField(blank=True, null=True, verbose_name='orthancImageCount')),
                ('orthancImageInsertionTime', models.DateTimeField(verbose_name='orthancImageInsertionTime')),
                ('orthancImageLastBuildTime', models.DateTimeField(verbose_name='orthancImageLastBuildTime')),
            ],
            options={
                'verbose_name': 'dds_data_record',
                'verbose_name_plural': 'dds_data_record',
                'db_table': 'DDS_data',
            },
        ),
        migrations.CreateModel(
            name='dds_host',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dds_ip', models.CharField(blank=True, max_length=30, null=True, verbose_name='dds_ip')),
            ],
            options={
                'verbose_name': 'dicommaster_host_record',
                'verbose_name_plural': 'dicommaster_host_record',
                'db_table': 'DDS_host',
            },
        ),
        migrations.AddField(
            model_name='dicom_record',
            name='server',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='服务'),
        ),
    ]
