# Generated by Django 2.1.7 on 2020-10-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0003_duration_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imagecount',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='imagecount'),
        ),
    ]
