# Generated by Django 2.1.7 on 2020-11-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0004_image_imagecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stress_data',
            name='imagecount',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='张数'),
        ),
        migrations.AlterField(
            model_name='stress_data',
            name='slicenumber',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='肺炎层厚'),
        ),
    ]
