# Generated by Django 2.1.7 on 2020-12-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0004_auto_20201201_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_data',
            name='status',
            field=models.BooleanField(default=True, verbose_name='0是关闭，1是启用'),
        ),
    ]
