# Generated by Django 2.1.7 on 2020-07-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0004_auto_20200720_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stress_record',
            name='block',
        ),
        migrations.AddField(
            model_name='stress_record',
            name='end_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='压测结束时间'),
        ),
        migrations.AddField(
            model_name='stress_record',
            name='start_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='压测开始时间'),
        ),
        migrations.AlterField(
            model_name='stress_record',
            name='loop_time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='执行时间'),
        ),
    ]
