# Generated by Django 2.1.7 on 2020-12-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0004_auto_20201216_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=30, null=True, verbose_name='文件名')),
                ('fileurl', models.CharField(blank=True, max_length=30, null=True, verbose_name='文件路径')),
                ('fileid', models.IntegerField(blank=True, max_length=10, null=True, verbose_name='关联文件id')),
                ('type', models.CharField(blank=True, max_length=30, null=True, verbose_name='类型')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'uploadfile',
                'verbose_name_plural': 'uploadfile',
                'db_table': 'uploadfile',
            },
        ),
    ]
