# Generated by Django 2.1.7 on 2020-08-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0005_auto_20200727_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='duration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('server', models.CharField(blank=True, max_length=20, null=True, verbose_name='服务器ip')),
                ('keyword', models.CharField(blank=True, max_length=20, null=True, verbose_name='匿名名称')),
                ('dicom', models.CharField(blank=True, max_length=20, null=True, verbose_name='dicom数据')),
                ('time', models.CharField(blank=True, max_length=20, null=True, verbose_name='发送时间')),
                ('status', models.CharField(blank=True, max_length=10, null=True, verbose_name='发送状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '持续化配置',
                'verbose_name_plural': '持续化配置',
                'db_table': 'duration',
            },
        ),
        migrations.AlterField(
            model_name='base_data',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='base_data',
            name='select_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='查询类型'),
        ),
        migrations.AlterField(
            model_name='base_data',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='类型'),
        ),
    ]
