# Generated by Django 2.1.7 on 2020-12-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0005_auto_20201201_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dicom_route',
        ),
        migrations.AddField(
            model_name='duration',
            name='route',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='路径'),
        ),
    ]
