# Generated by Django 2.1.7 on 2020-12-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0005_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='stress',
            name='jmeterstatus',
            field=models.BooleanField(default=True, verbose_name='jmeter状态'),
        ),
    ]
