# Generated by Django 2.1.7 on 2020-11-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0005_auto_20201103_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stress_data',
            name='slicenumber',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='肺炎层厚'),
        ),
    ]
