# Generated by Django 2.1.7 on 2020-08-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0005_auto_20200826_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration',
            name='dicom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='dicom数据'),
        ),
    ]
