# Generated by Django 2.1.7 on 2020-12-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0006_stress_jmeterstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='duration_record',
            name='endtime',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='发送结束时间'),
        ),
        migrations.AddField(
            model_name='duration_record',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='duration',
            name='aet',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='aet'),
        ),
        migrations.AlterField(
            model_name='duration',
            name='keyword',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='匿名名称'),
        ),
        migrations.AlterField(
            model_name='duration',
            name='port',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='服务器端口号'),
        ),
        migrations.AlterField(
            model_name='duration_record',
            name='sendtime',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='发送开始时间'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='fileid',
            field=models.IntegerField(blank=True, null=True, verbose_name='关联文件id'),
        ),
    ]
