# Generated by Django 2.1.7 on 2020-12-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0006_auto_20201201_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicom',
            name='predictor',
        ),
        migrations.AddField(
            model_name='dicom',
            name='fileid',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='文件ID'),
        ),
    ]
