# Generated by Django 2.1.7 on 2020-11-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0006_auto_20201104_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stress_data',
            name='vote',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='挂载'),
        ),
    ]
