# Generated by Django 2.1.7 on 2020-09-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0007_duration_record_studyolduid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duration_record',
            old_name='time',
            new_name='duration_id',
        ),
    ]
