# Generated by Django 2.1.7 on 2020-12-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0007_auto_20201221_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='stress_record',
            name='benchmarkstatus',
            field=models.BooleanField(default=False, verbose_name='是否基准'),
        ),
        migrations.AddField(
            model_name='stress_record',
            name='status',
            field=models.BooleanField(default=False, verbose_name='状态'),
        ),
    ]
