# Generated by Django 2.1.7 on 2020-11-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0007_auto_20201105_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='stress_data',
            name='server',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='服务'),
        ),
    ]
