# Generated by Django 2.1.7 on 2020-12-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0008_auto_20201221_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='stress_job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, max_length=10, null=True, verbose_name='版本')),
                ('studyuid', models.CharField(blank=True, max_length=200, null=True, verbose_name='uid')),
                ('type', models.CharField(blank=True, max_length=15, null=True, verbose_name='类型')),
                ('job_id', models.CharField(blank=True, max_length=6, null=True, verbose_name='id')),
                ('sec', models.IntegerField(blank=True, null=True, verbose_name='秒')),
                ('start', models.CharField(blank=True, max_length=20, null=True, verbose_name='开始时间')),
                ('end', models.CharField(blank=True, max_length=20, null=True, verbose_name='结束时间')),
                ('modelname', models.CharField(blank=True, max_length=30, null=True, verbose_name='模型名称')),
                ('stressid', models.IntegerField(blank=True, null=True, verbose_name='stressID')),
            ],
            options={
                'verbose_name': '压测结果记录表',
                'verbose_name_plural': '压测结果记录表',
                'db_table': 'stress_job',
            },
        ),
        migrations.AddField(
            model_name='stress_result',
            name='stressid',
            field=models.IntegerField(blank=True, null=True, verbose_name='stressID'),
        ),
        migrations.AlterField(
            model_name='stress_result',
            name='avgimages',
            field=models.TextField(blank=True, max_length=10, null=True, verbose_name='影像张数'),
        ),
        migrations.AlterField(
            model_name='stress_result',
            name='maximages',
            field=models.TextField(blank=True, max_length=10, null=True, verbose_name='影像张数'),
        ),
        migrations.AlterField(
            model_name='stress_result',
            name='minimages',
            field=models.TextField(blank=True, max_length=10, null=True, verbose_name='影像张数'),
        ),
    ]
