# Generated by Django 2.1.7 on 2020-12-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0009_auto_20201221_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='stress_job',
            name='images',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='模型名称'),
        ),
        migrations.AlterField(
            model_name='stress_job',
            name='job_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='stress_job',
            name='sec',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='预测时间'),
        ),
        migrations.AlterField(
            model_name='stress_job',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='stress_job',
            name='version',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='版本'),
        ),
    ]
