# Generated by Django 2.1.7 on 2020-09-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0009_auto_20200901_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration_record',
            name='aistatus',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='AI预测结果'),
        ),
        migrations.AlterField(
            model_name='duration_record',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='诊断结果'),
        ),
        migrations.AlterField(
            model_name='duration_record',
            name='duration_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='关联持续id'),
        ),
        migrations.AlterField(
            model_name='duration_record',
            name='imagecount',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='发送影像张数'),
        ),
        migrations.AlterField(
            model_name='duration_record',
            name='imagecount_server',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='接收影像张数'),
        ),
    ]
