# Generated by Django 2.1.7 on 2020-12-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0010_auto_20201221_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalhost',
            name='protocol',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='协议'),
        ),
        migrations.AlterField(
            model_name='stress_job',
            name='end',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='stress_job',
            name='job_id',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='stress_job',
            name='start',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='开始时间'),
        ),
    ]
