# Generated by Django 2.1.7 on 2020-12-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0011_auto_20201224_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='duration',
            name='hostid',
            field=models.IntegerField(default=True, verbose_name='HOST id'),
        ),
        migrations.AddField(
            model_name='stress',
            name='hostid',
            field=models.IntegerField(default=True, verbose_name='HOST id'),
        ),
    ]
