# Generated by Django 2.1.7 on 2020-09-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0011_auto_20200902_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration',
            name='pid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='进程号'),
        ),
    ]
