# Generated by Django 2.1.7 on 2020-12-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0012_auto_20201228_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicom_record',
            name='hostid',
            field=models.IntegerField(default=False, verbose_name='hostid'),
        ),
    ]
