# Generated by Django 2.1.7 on 2020-09-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0012_auto_20200902_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duration',
            name='time',
        ),
        migrations.AddField(
            model_name='duration',
            name='end_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='duration_record',
            name='sendtime',
            field=models.DateTimeField(blank=True, max_length=20, null=True, verbose_name='发送时间'),
        ),
    ]
