# Generated by Django 2.1.7 on 2020-12-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0013_dicom_record_hostid'),
    ]

    operations = [
        migrations.AddField(
            model_name='stress_record',
            name='fileurl',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=' 路径'),
        ),
    ]
