# Generated by Django 2.1.7 on 2020-09-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0013_auto_20200903_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration_record',
            name='sendtime',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='发送时间'),
        ),
    ]
