# Generated by Django 2.1.7 on 2020-09-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0014_auto_20200907_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration_record',
            name='accessionnumber',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='accessionnumber'),
        ),
        migrations.AlterField(
            model_name='duration_record',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='诊断结果'),
        ),
        migrations.AlterField(
            model_name='duration_record',
            name='duration_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='关联持续id'),
        ),
        migrations.AlterField(
            model_name='duration_record',
            name='patientid',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='patientid'),
        ),
        migrations.AlterField(
            model_name='duration_record',
            name='studyinstanceuid',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='数据uid'),
        ),
    ]
