# Generated by Django 2.1.7 on 2021-01-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0014_stress_record_fileurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='smoke',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, max_length=20, null=True, verbose_name='版本')),
                ('diseases', models.CharField(blank=True, max_length=20, null=True, verbose_name='病种')),
                ('aistatus', models.CharField(blank=True, max_length=5, null=True, verbose_name='预测结果')),
                ('starttime', models.CharField(blank=True, max_length=20, null=True, verbose_name='开始预测时间')),
                ('completiontime', models.CharField(blank=True, max_length=20, null=True, verbose_name='结束预测时间')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('hostid', models.IntegerField(default=False, verbose_name='hostid')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'smoke测试表',
                'verbose_name_plural': 'smoke测试表',
                'db_table': 'smoke',
            },
        ),
    ]
