# Generated by Django 2.1.7 on 2020-09-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0015_auto_20200907_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='stress_result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, max_length=10, null=True, verbose_name='版本')),
                ('modelname', models.CharField(blank=True, max_length=30, null=True, verbose_name='模型')),
                ('type', models.CharField(blank=True, max_length=15, null=True, verbose_name='结果类型')),
                ('slicenumber', models.CharField(blank=True, max_length=6, null=True, verbose_name='层厚')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='次数')),
                ('avg', models.CharField(blank=True, max_length=10, null=True, verbose_name='平均值')),
                ('single', models.CharField(blank=True, max_length=10, null=True, verbose_name='单任务')),
                ('median', models.CharField(blank=True, max_length=10, null=True, verbose_name='中间值')),
                ('min', models.CharField(blank=True, max_length=10, null=True, verbose_name='最小时间')),
                ('max', models.CharField(blank=True, max_length=10, null=True, verbose_name='最大时间')),
                ('coef', models.CharField(blank=True, max_length=10, null=True, verbose_name='系数')),
                ('rate', models.TextField(blank=True, max_length=10, null=True, verbose_name='预测成功率')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '压测结果记录表',
                'verbose_name_plural': '压测结果记录表',
                'db_table': 'stress_result',
            },
        ),
        migrations.AlterField(
            model_name='duration_record',
            name='studyolduid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='影像张数验证'),
        ),
    ]
