# Generated by Django 2.1.7 on 2020-09-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0016_auto_20200910_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='pid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField(blank=True, null=True, verbose_name='进程号')),
                ('durationid', models.CharField(blank=True, max_length=5, null=True, verbose_name='持续化id')),
            ],
            options={
                'verbose_name': 'pid表',
                'verbose_name_plural': 'pid表',
                'db_table': 'pid',
            },
        ),
    ]
