# Generated by Django 2.1.7 on 2021-01-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0016_auto_20210104_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smoke',
            name='aistatus',
        ),
        migrations.AddField(
            model_name='smoke',
            name='progress',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='进度'),
        ),
        migrations.AddField(
            model_name='smoke',
            name='thread',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='线程数'),
        ),
    ]
