# Generated by Django 2.1.7 on 2021-01-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0017_auto_20210104_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold',
            name='count',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='count'),
        ),
    ]
