# Generated by Django 2.1.7 on 2020-09-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0017_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duration',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='duration',
            name='pid',
        ),
        migrations.AddField(
            model_name='duration',
            name='sendcount',
            field=models.IntegerField(blank=True, null=True, verbose_name='共计发送'),
        ),
        migrations.AddField(
            model_name='duration',
            name='timer',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='定时器'),
        ),
    ]
