# Generated by Django 2.1.7 on 2020-09-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0018_auto_20200914_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_data',
            name='other',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='其他'),
        ),
        migrations.AddField(
            model_name='duration',
            name='dds',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
