# Generated by Django 2.1.7 on 2021-01-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0019_auto_20210105_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='smoke_record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, max_length=10, null=True, verbose_name='版本')),
                ('patientid', models.CharField(blank=True, max_length=50, null=True, verbose_name='id')),
                ('patientname', models.CharField(blank=True, max_length=50, null=True, verbose_name='id')),
                ('studyinstanceuid', models.CharField(blank=True, max_length=150, null=True, verbose_name='数据uid')),
                ('diseases', models.CharField(blank=True, max_length=20, null=True, verbose_name='病种')),
                ('slicenumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='slicenumber')),
                ('aistatus', models.CharField(blank=True, max_length=5, null=True, verbose_name='预测结果')),
                ('aidiagnosis', models.CharField(blank=True, max_length=100, null=True, verbose_name='ai诊断结果')),
                ('diagnosis', models.CharField(blank=True, max_length=100, null=True, verbose_name='诊断结果')),
                ('starttime', models.CharField(blank=True, max_length=20, null=True, verbose_name='开始预测时间')),
                ('completiontime', models.CharField(blank=True, max_length=20, null=True, verbose_name='结束预测时间')),
                ('result', models.TextField(blank=True, max_length=2500, null=True, verbose_name='结果')),
                ('type', models.TextField(blank=True, max_length=10, null=True, verbose_name='类型')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('smokeid', models.IntegerField(default=False, verbose_name='smokeid')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '冒烟测试记录表',
                'verbose_name_plural': '冒烟测试记录表',
                'db_table': 'smoke_record',
            },
        ),
    ]
