# Generated by Django 2.1.7 on 2021-01-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0019_auto_20210105_1049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dds_host',
        ),
    ]
