# Generated by Django 2.1.7 on 2020-09-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0019_auto_20200914_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration',
            name='dds',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='dds 服务'),
        ),
        migrations.AlterField(
            model_name='duration',
            name='status',
            field=models.BooleanField(default=False, verbose_name='状态'),
        ),
    ]
