# Generated by Django 2.1.7 on 2020-09-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0020_auto_20200916_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stress_record',
            name='testdata',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='测试数据'),
        ),
    ]
