# Generated by Django 2.1.7 on 2021-01-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0020_smoke_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duration',
            name='keyword',
        ),
        migrations.AddField(
            model_name='duration',
            name='anonymous',
            field=models.BooleanField(default=True, verbose_name='anonymous'),
        ),
        migrations.AddField(
            model_name='duration',
            name='patientid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='patientid'),
        ),
        migrations.AddField(
            model_name='duration',
            name='patientname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='patientname'),
        ),
    ]
