# Generated by Django 2.1.7 on 2020-09-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0021_auto_20200924_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration_record',
            name='studyinstanceuid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='数据uid'),
        ),
        migrations.AlterField(
            model_name='duration_record',
            name='studyolduid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='影像张数验证'),
        ),
    ]
