# Generated by Django 2.1.7 on 2021-01-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0021_auto_20210114_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='autoui',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('i', models.CharField(blank=True, max_length=20, null=True, verbose_name='版本')),
                ('cases', models.CharField(blank=True, max_length=20, null=True, verbose_name='用例')),
                ('progress', models.CharField(blank=True, max_length=5, null=True, verbose_name='进度')),
                ('thread', models.CharField(blank=True, max_length=5, null=True, verbose_name='线程数')),
                ('starttime', models.CharField(blank=True, max_length=20, null=True, verbose_name='开始预测时间')),
                ('completiontime', models.CharField(blank=True, max_length=20, null=True, verbose_name='结束预测时间')),
                ('total', models.CharField(blank=True, max_length=5, null=True, verbose_name='count')),
                ('hostid', models.IntegerField(default=False, verbose_name='hostid')),
                ('report', models.CharField(blank=True, max_length=80, null=True, verbose_name='报告')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
            ],
            options={
                'verbose_name': 'autoui测试表',
                'verbose_name_plural': 'autoui测试表',
                'db_table': 'autou',
            },
        ),
        migrations.CreateModel(
            name='autoui_case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('casename', models.CharField(blank=True, max_length=50, null=True, verbose_name='用例名称')),
                ('testdata', models.CharField(blank=True, max_length=30, null=True, verbose_name='关联测试数据')),
                ('url', models.TextField(blank=True, max_length=100, null=True, verbose_name='结果')),
                ('type', models.TextField(blank=True, max_length=10, null=True, verbose_name='类型')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'autoui case 表',
                'verbose_name_plural': 'autoui case 表',
                'db_table': 'autoui_case',
            },
        ),
    ]
