# Generated by Django 2.1.7 on 2021-01-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0022_autoui_autoui_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='auto_record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aistatus', models.CharField(blank=True, max_length=5, null=True, verbose_name='预测结果')),
                ('starttime', models.CharField(blank=True, max_length=20, null=True, verbose_name='开始时间')),
                ('completiontime', models.CharField(blank=True, max_length=20, null=True, verbose_name='结束时间')),
                ('result', models.TextField(blank=True, max_length=2500, null=True, verbose_name='结果')),
                ('type', models.TextField(blank=True, max_length=10, null=True, verbose_name='类型')),
                ('caseid', models.IntegerField(default=False, verbose_name='caseid')),
                ('testid', models.IntegerField(default=False, verbose_name='关联测试数据')),
                ('autoid', models.IntegerField(default=False, verbose_name='autoid')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'auto_record',
                'verbose_name_plural': 'auto_record',
                'db_table': 'auto_record',
            },
        ),
        migrations.CreateModel(
            name='autotest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, max_length=20, null=True, verbose_name='版本')),
                ('cases', models.CharField(blank=True, max_length=20, null=True, verbose_name='用例')),
                ('progress', models.CharField(blank=True, max_length=5, null=True, verbose_name='进度')),
                ('thread', models.CharField(blank=True, max_length=5, null=True, verbose_name='线程数')),
                ('starttime', models.CharField(blank=True, max_length=20, null=True, verbose_name='开始预测时间')),
                ('completiontime', models.CharField(blank=True, max_length=20, null=True, verbose_name='结束预测时间')),
                ('total', models.CharField(blank=True, max_length=5, null=True, verbose_name='count')),
                ('hostid', models.IntegerField(default=False, verbose_name='hostid')),
                ('report', models.CharField(blank=True, max_length=80, null=True, verbose_name='报告')),
                ('type', models.CharField(blank=True, max_length=10, null=True, verbose_name='类型')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
            ],
            options={
                'verbose_name': 'autotest测试表',
                'verbose_name_plural': 'autotest测试表',
                'db_table': 'autotest',
            },
        ),
        migrations.DeleteModel(
            name='autoui',
        ),
        migrations.DeleteModel(
            name='autoui_case',
        ),
    ]
