# Generated by Django 2.1.7 on 2021-01-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0023_auto_20210116_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='auto_case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='名称')),
                ('testdata', models.CharField(blank=True, max_length=100, null=True, verbose_name='关联测试数据')),
                ('type', models.CharField(blank=True, max_length=10, null=True, verbose_name='类型')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'auto_case',
                'verbose_name_plural': 'auto_case',
                'db_table': 'auto_case',
            },
        ),
    ]
