# Generated by Django 2.1.7 on 2021-01-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0024_auto_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotest',
            name='setup',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='setup用例'),
        ),
        migrations.AddField(
            model_name='autotest',
            name='tearDown',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='tearDown用例'),
        ),
    ]
