# Generated by Django 2.1.7 on 2021-01-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0025_auto_20210118_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smoke',
            name='diseases',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='病种'),
        ),
    ]
