# Generated by Django 2.1.7 on 2021-01-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0026_auto_20210120_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smoke',
            name='diseases',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='病种'),
        ),
    ]
