# Generated by Django 2.1.7 on 2021-01-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0027_auto_20210123_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicom',
            name='status',
            field=models.BooleanField(default=False, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='dicom',
            name='stressstatus',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='性能状态'),
        ),
    ]
