# Generated by Django 2.1.7 on 2021-01-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0028_auto_20210125_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='stress_job',
            name='slicenumber',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='层厚'),
        ),
        migrations.AlterField(
            model_name='stress_job',
            name='images',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='张数'),
        ),
    ]
