# Generated by Django 2.1.7 on 2021-01-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0029_auto_20210127_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smoke_record',
            name='aistatus',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='预测结果'),
        ),
        migrations.AlterField(
            model_name='smoke_record',
            name='diseases',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='病种'),
        ),
        migrations.AlterField(
            model_name='smoke_record',
            name='patientid',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='smoke_record',
            name='patientname',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='smoke_record',
            name='type',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='smoke_record',
            name='version',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='版本'),
        ),
    ]
