# Generated by Django 2.1.7 on 2021-01-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0030_auto_20210127_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stress_job',
            name='end',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='stress_job',
            name='start',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='开始时间'),
        ),
    ]
