# Generated by Django 2.1.7 on 2021-02-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0032_auto_20210208_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicom',
            name='server',
        ),
        migrations.AddField(
            model_name='dicom',
            name='predictor',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='模型'),
        ),
    ]
