# Generated by Django 2.1.7 on 2021-02-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0033_auto_20210219_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='id',
            new_name='stressid',
        ),
        migrations.RenameField(
            model_name='stress_record',
            old_name='id',
            new_name='recordid',
        ),
        migrations.AddField(
            model_name='stress_job',
            name='aistatus',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='预测状态'),
        ),
    ]
