# Generated by Django 2.1.7 on 2021-02-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0034_auto_20210223_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto_case',
            old_name='id',
            new_name='caseid',
        ),
        migrations.RenameField(
            model_name='auto_record',
            old_name='id',
            new_name='recordid',
        ),
        migrations.RenameField(
            model_name='autotest',
            old_name='id',
            new_name='autoid',
        ),
        migrations.RemoveField(
            model_name='auto_record',
            name='testid',
        ),
        migrations.AddField(
            model_name='auto_record',
            name='actual',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='实际结果'),
        ),
        migrations.AddField(
            model_name='auto_record',
            name='expect',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='预期结果'),
        ),
        migrations.AddField(
            model_name='auto_record',
            name='server',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='服务'),
        ),
        migrations.AddField(
            model_name='auto_record',
            name='studyuid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='studyuid'),
        ),
        migrations.AddField(
            model_name='auto_record',
            name='vote',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='挂载'),
        ),
        migrations.AlterField(
            model_name='auto_record',
            name='result',
            field=models.TextField(blank=True, max_length=2500, null=True, verbose_name='结论'),
        ),
    ]
