# Generated by Django 2.1.7 on 2021-02-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0035_auto_20210225_1024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auto_case',
        ),
        migrations.DeleteModel(
            name='auto_record',
        ),
        migrations.DeleteModel(
            name='autotest',
        )
    ]
