# Generated by Django 2.1.7 on 2021-03-03 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0036_auto_20210225_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
        migrations.DeleteModel(
            name='stress_job',
        ),
        migrations.DeleteModel(
            name='stress_record',
        ),
        migrations.DeleteModel(
            name='stress_result',
        ),
    ]
