# Generated by Django 2.1.7 on 2021-03-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0038_auto_20210308_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='install',
            name='smokeid',
            field=models.IntegerField(blank=True, null=True, verbose_name='smokeid'),
        ),
        migrations.AddField(
            model_name='install',
            name='uid',
            field=models.IntegerField(blank=True, null=True, verbose_name='UIuid'),
        ),
    ]
