# Generated by Django 2.1.7 on 2021-03-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0039_auto_20210310_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='install',
            name='installstatus',
            field=models.BooleanField(default=False, verbose_name='部署状态 0升级安装 1全新安装'),
        ),
    ]
