# Generated by Django 2.1.7 on 2021-03-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0040_auto_20210316_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='install',
            name='crontab',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='类型'),
        ),
    ]
