# Generated by Django 2.1.7 on 2021-04-27 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AutoProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiGroupLevelFirst',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='接口一级分组名称')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoProject.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '接口分组',
                'verbose_name_plural': '接口分组',
                'db_table': 'ApiGroupLevelFirst',
            },
        ),
        migrations.CreateModel(
            name='ApiHead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024, verbose_name='标签')),
                ('value', models.CharField(blank=True, max_length=1024, null=True, verbose_name='内容')),
            ],
            options={
                'verbose_name': '请求头',
                'verbose_name_plural': '请求头管理',
                'db_table': 'ApiHead',
            },
        ),
        migrations.CreateModel(
            name='ApiInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='接口名称')),
                ('httpType', models.CharField(choices=[('HTTP', 'HTTP'), ('HTTPS', 'HTTPS')], default='HTTP', max_length=50, verbose_name='http/https')),
                ('requestType', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=50, verbose_name='请求方式')),
                ('apiAddress', models.CharField(max_length=1024, verbose_name='接口地址')),
                ('requestParameterType', models.CharField(choices=[('form-data', '表单(form-data)'), ('raw', '源数据(raw)'), ('Restful', 'Restful')], max_length=50, verbose_name='请求参数格式')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('mockStatus', models.BooleanField(default=False, verbose_name='mock状态')),
                ('mockCode', models.CharField(blank=True, choices=[('200', '200'), ('404', '404'), ('400', '400'), ('502', '502'), ('500', '500'), ('302', '302')], max_length=50, null=True, verbose_name='HTTP状态')),
                ('data', models.TextField(blank=True, null=True, verbose_name='mock内容')),
                ('lastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='最近更新')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('apiGroupLevelFirst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='First', to='AutoInterface.ApiGroupLevelFirst', verbose_name='所属一级分组')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_project', to='AutoProject.Project', verbose_name='所属项目')),
                ('userUpdate', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ApiUpdateUser', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '接口',
                'verbose_name_plural': '接口管理',
                'db_table': 'ApiInfo',
            },
        ),
        migrations.CreateModel(
            name='ApiOperationHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='操作内容')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoInterface.ApiInfo', verbose_name='接口')),
                ('user', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户姓名')),
            ],
            options={
                'verbose_name': '接口操作历史',
                'verbose_name_plural': '接口操作历史',
                'db_table': 'ApiOperationHistory',
            },
        ),
        migrations.CreateModel(
            name='ApiParameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024, verbose_name='参数名')),
                ('_type', models.CharField(choices=[('Int', 'Int'), ('String', 'String')], default='String', max_length=1024, verbose_name='参数类型')),
                ('value', models.CharField(blank=True, max_length=1024, null=True, verbose_name='参数值')),
                ('required', models.BooleanField(default=True, verbose_name='是否必填')),
                ('restrict', models.CharField(blank=True, max_length=1024, null=True, verbose_name='输入限制')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestParameter', to='AutoInterface.ApiInfo', verbose_name='所属接口')),
            ],
            options={
                'verbose_name': '请求参数',
                'verbose_name_plural': '请求参数管理',
                'db_table': 'ApiParameter',
            },
        ),
        migrations.CreateModel(
            name='ApiParameterRaw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('api', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requestParameterRaw', to='AutoInterface.ApiInfo', verbose_name='所属接口')),
            ],
            options={
                'verbose_name': '请求参数Raw',
                'db_table': 'ApiParameterRaw',
            },
        ),
        migrations.CreateModel(
            name='APIRequestHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requestTime', models.DateTimeField(auto_now_add=True, verbose_name='请求时间')),
                ('requestType', models.CharField(max_length=50, verbose_name='请求方法')),
                ('requestAddress', models.CharField(max_length=1024, verbose_name='请求地址')),
                ('httpCode', models.CharField(max_length=50, verbose_name='HTTP状态')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoInterface.ApiInfo', verbose_name='接口')),
            ],
            options={
                'verbose_name': '接口请求历史',
                'verbose_name_plural': '接口请求历史',
                'db_table': 'APIRequestHistory',
            },
        ),
        migrations.CreateModel(
            name='ApiResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024, verbose_name='参数名')),
                ('_type', models.CharField(choices=[('Int', 'Int'), ('String', 'String')], default='String', max_length=1024, verbose_name='参数类型')),
                ('value', models.CharField(blank=True, max_length=1024, null=True, verbose_name='参数值')),
                ('required', models.BooleanField(default=True, verbose_name='是否必含')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='AutoInterface.ApiInfo', verbose_name='所属接口')),
            ],
            options={
                'verbose_name': '返回参数',
                'verbose_name_plural': '返回参数管理',
                'db_table': 'ApiResponse',
            },
        ),
        migrations.CreateModel(
            name='AutomationCaseApi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='接口名称')),
                ('httpType', models.CharField(choices=[('HTTP', 'HTTP'), ('HTTPS', 'HTTPS')], default='HTTP', max_length=50, verbose_name='HTTP/HTTPS')),
                ('requestType', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=50, verbose_name='请求方式')),
                ('apiAddress', models.CharField(max_length=1024, verbose_name='接口地址')),
                ('requestParameterType', models.CharField(choices=[('form-data', '表单(form-data)'), ('raw', '源数据(raw)'), ('Restful', 'Restful')], max_length=50, verbose_name='参数请求格式')),
                ('formatRaw', models.BooleanField(default=False, verbose_name='是否转换成源数据')),
                ('examineType', models.CharField(choices=[('no_check', '不校验'), ('only_check_status', '校验http状态'), ('json', 'JSON校验'), ('entirely_check', '完全校验'), ('Regular_check', '正则校验')], default='no_check', max_length=50, verbose_name='校验方式')),
                ('httpCode', models.CharField(blank=True, choices=[('200', '200'), ('404', '404'), ('400', '400'), ('502', '502'), ('500', '500'), ('302', '302')], max_length=50, null=True, verbose_name='HTTP状态')),
                ('responseData', models.TextField(blank=True, null=True, verbose_name='返回内容')),
            ],
            options={
                'verbose_name': '用例接口',
                'verbose_name_plural': '用例接口管理',
                'db_table': 'AutomationCaseApi',
            },
        ),
        migrations.CreateModel(
            name='AutomationCaseTestResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('header', models.CharField(blank=True, max_length=1024, null=True, verbose_name='请求头')),
                ('parameter', models.TextField(blank=True, null=True, verbose_name='请求参数')),
                ('result', models.CharField(choices=[('PASS', '成功'), ('FAIL', '失败')], max_length=50, verbose_name='测试结果')),
                ('httpStatus', models.CharField(blank=True, choices=[('200', '200'), ('404', '404'), ('400', '400'), ('502', '502'), ('500', '500'), ('302', '302')], max_length=50, null=True, verbose_name='http状态')),
                ('responseHeader', models.TextField(blank=True, null=True, verbose_name='返回头')),
                ('responseData', models.TextField(blank=True, null=True, verbose_name='实际返回内容')),
                ('testTime', models.CharField(blank=True, max_length=128, null=True, verbose_name='测试时间')),
                ('automationCaseApi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_result', to='AutoInterface.AutomationCaseApi', verbose_name='接口')),
            ],
            options={
                'verbose_name': '自动测试结果',
                'verbose_name_plural': '自动测试结果管理',
                'db_table': 'AutomationCaseTestResult',
            },
        ),
        migrations.CreateModel(
            name='AutomationGroupLevelFirst',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='用例一级分组')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoProject.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '用例分组',
                'verbose_name_plural': '用例分组管理',
                'db_table': 'AutomationGroupLevelFirst',
            },
        ),
        migrations.CreateModel(
            name='AutomationHead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024, verbose_name='参数名')),
                ('value', models.CharField(max_length=1024, verbose_name='内容')),
                ('interrelate', models.BooleanField(default=False, verbose_name='是否关联')),
                ('automationCaseApi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header', to='AutoInterface.AutomationCaseApi', verbose_name='接口')),
            ],
            options={
                'verbose_name': '请求头',
                'verbose_name_plural': '请求头管理',
                'db_table': 'AutomationHead',
            },
        ),
        migrations.CreateModel(
            name='AutomationParameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024, verbose_name='参数名')),
                ('value', models.CharField(blank=True, max_length=1024, null=True, verbose_name='内容')),
                ('interrelate', models.BooleanField(default=False, verbose_name='是否关联')),
                ('automationCaseApi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameterList', to='AutoInterface.AutomationCaseApi', verbose_name='接口')),
            ],
            options={
                'verbose_name': '接口参数',
                'verbose_name_plural': '接口参数管理',
                'db_table': 'AutomationParameter',
            },
        ),
        migrations.CreateModel(
            name='AutomationParameterRaw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.TextField(blank=True, null=True, verbose_name='源数据请求参数')),
                ('automationCaseApi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parameterRaw', to='AutoInterface.AutomationCaseApi', verbose_name='接口')),
            ],
            options={
                'verbose_name': '源数据参数',
                'verbose_name_plural': '源数据参数管理',
                'db_table': 'AutomationParameterRaw',
            },
        ),
        migrations.CreateModel(
            name='AutomationReportSendConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reportFrom', models.EmailField(blank=True, max_length=1024, null=True, verbose_name='发送人邮箱')),
                ('mailUser', models.CharField(blank=True, max_length=1024, null=True, verbose_name='用户名')),
                ('mailPass', models.CharField(blank=True, max_length=1024, null=True, verbose_name='口令')),
                ('mailSmtp', models.CharField(blank=True, max_length=1024, null=True, verbose_name='邮箱服务器')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AutoProject.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '邮件发送配置',
                'verbose_name_plural': '邮件发送配置',
                'db_table': 'AutomationReportSendConfig',
            },
        ),
        migrations.CreateModel(
            name='AutomationResponseJson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='JSON参数')),
                ('tier', models.CharField(blank=True, max_length=1024, null=True, verbose_name='层级关系')),
                ('type', models.CharField(choices=[('json', 'json'), ('Regular', 'Regular')], default='json', max_length=1024, verbose_name='关联类型')),
                ('automationCaseApi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='AutoInterface.AutomationCaseApi', verbose_name='接口')),
            ],
            options={
                'verbose_name': '结果JSON参数',
                'verbose_name_plural': '结果JSON参数管理',
                'db_table': 'AutomationResponseJson',
            },
        ),
        migrations.CreateModel(
            name='AutomationTaskRunTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startTime', models.CharField(max_length=50, verbose_name='开始时间')),
                ('host', models.CharField(blank=True, max_length=1024, null=True, verbose_name='测试地址')),
                ('elapsedTime', models.CharField(max_length=50, verbose_name='结束时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoProject.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '用例任务执行时间',
                'verbose_name_plural': '用例任务执行时间',
                'db_table': 'AutomationTaskRunTime',
            },
        ),
        migrations.CreateModel(
            name='AutomationTestCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caseName', models.CharField(max_length=50, verbose_name='用例名称')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('automationGroupLevelFirst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automationGroup', to='AutoInterface.AutomationGroupLevelFirst', verbose_name='所属用例一级分组')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoProject.Project', verbose_name='所属项目')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createUser', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '自动化测试用例',
                'verbose_name_plural': '自动化测试用例',
                'db_table': 'AutomationTestCase',
            },
        ),
        migrations.CreateModel(
            name='AutomationTestResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1024, verbose_name='请求地址')),
                ('requestType', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=1024, verbose_name='请求方式')),
                ('host', models.CharField(blank=True, max_length=1024, null=True, verbose_name='测试地址')),
                ('header', models.CharField(blank=True, max_length=1024, null=True, verbose_name='请求头')),
                ('parameter', models.TextField(blank=True, null=True, verbose_name='请求参数')),
                ('statusCode', models.CharField(blank=True, choices=[('200', '200'), ('404', '404'), ('400', '400'), ('502', '502'), ('500', '500'), ('302', '302')], max_length=1024, null=True, verbose_name='期望HTTP状态')),
                ('examineType', models.CharField(max_length=1024, verbose_name='匹配规则')),
                ('data', models.TextField(blank=True, null=True, verbose_name='规则内容')),
                ('result', models.CharField(choices=[('PASS', '成功'), ('FAIL', '失败')], max_length=50, verbose_name='测试结果')),
                ('httpStatus', models.CharField(blank=True, choices=[('200', '200'), ('404', '404'), ('400', '400'), ('502', '502'), ('500', '500'), ('302', '302')], max_length=50, null=True, verbose_name='http状态')),
                ('responseData', models.TextField(blank=True, null=True, verbose_name='实际返回内容')),
                ('testTime', models.DateTimeField(auto_now_add=True, verbose_name='测试时间')),
                ('automationCaseApi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_result', to='AutoInterface.AutomationCaseApi', verbose_name='接口')),
            ],
            options={
                'verbose_name': '手动测试结果',
                'verbose_name_plural': '手动测试结果管理',
                'db_table': 'AutomationTestResult',
            },
        ),
        migrations.CreateModel(
            name='AutomationTestTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='任务名称')),
                ('type', models.CharField(choices=[('circulation', '循环'), ('timing', '定时')], max_length=50, verbose_name='类型')),
                ('frequency', models.IntegerField(blank=True, null=True, verbose_name='间隔')),
                ('unit', models.CharField(blank=True, choices=[('m', '分'), ('h', '时'), ('d', '天'), ('w', '周')], max_length=50, null=True, verbose_name='单位')),
                ('startTime', models.DateTimeField(max_length=50, verbose_name='开始时间')),
                ('endTime', models.DateTimeField(max_length=50, verbose_name='结束时间')),
                ('Host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoProject.Server', verbose_name='HOST')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AutoProject.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '用例定时任务',
                'verbose_name_plural': '用例定时任务管理',
                'db_table': 'AutomationTestTask',
            },
        ),
        migrations.CreateModel(
            name='CustomMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='方法名')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('type', models.CharField(max_length=50, verbose_name='类型')),
                ('dataCode', models.TextField(verbose_name='代码')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoProject.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '自定义方法',
                'verbose_name_plural': '自定义方法',
                'db_table': 'CustomMethod',
            },
        ),
        migrations.CreateModel(
            name='gold_record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, max_length=30, null=True, verbose_name='version')),
                ('patientid', models.CharField(blank=True, max_length=80, null=True, verbose_name='id')),
                ('patientname', models.CharField(blank=True, max_length=80, null=True, verbose_name='id')),
                ('studyinstanceuid', models.CharField(blank=True, max_length=150, null=True, verbose_name='数据uid')),
                ('diseases', models.CharField(blank=True, max_length=30, null=True, verbose_name='病种')),
                ('slicenumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='slicenumber')),
                ('aistatus', models.CharField(blank=True, max_length=10, null=True, verbose_name='预测结果')),
                ('aidiagnosis', models.CharField(blank=True, max_length=100, null=True, verbose_name='ai诊断结果')),
                ('diagnosis', models.CharField(blank=True, max_length=100, null=True, verbose_name='诊断结果')),
                ('starttime', models.CharField(blank=True, max_length=20, null=True, verbose_name='开始预测时间')),
                ('completiontime', models.CharField(blank=True, max_length=20, null=True, verbose_name='结束预测时间')),
                ('result', models.TextField(blank=True, max_length=2500, null=True, verbose_name='结果')),
                ('type', models.TextField(blank=True, max_length=20, null=True, verbose_name='类型')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '冒烟测试记录表',
                'verbose_name_plural': '冒烟测试记录表',
                'db_table': 'gold_record',
            },
        ),
        migrations.CreateModel(
            name='gold_test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, max_length=20, null=True, verbose_name='版本')),
                ('diseases', models.CharField(blank=True, max_length=80, null=True, verbose_name='病种')),
                ('progress', models.CharField(blank=True, max_length=5, null=True, verbose_name='进度')),
                ('thread', models.CharField(blank=True, max_length=5, null=True, verbose_name='线程数')),
                ('starttime', models.CharField(blank=True, max_length=20, null=True, verbose_name='开始预测时间')),
                ('completiontime', models.CharField(blank=True, max_length=20, null=True, verbose_name='结束预测时间')),
                ('count', models.CharField(blank=True, max_length=5, null=True, verbose_name='count')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('Host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AutoProject.Server', verbose_name='Host_id')),
            ],
            options={
                'verbose_name': 'gold_test测试表',
                'verbose_name_plural': 'gold_test测试表',
                'db_table': 'gold_test',
            },
        ),
        migrations.AddField(
            model_name='gold_record',
            name='gold',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AutoInterface.gold_test', verbose_name='gold_id'),
        ),
        migrations.AddField(
            model_name='automationcaseapi',
            name='automationTestCase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api', to='AutoInterface.AutomationTestCase', verbose_name='用例'),
        ),
        migrations.AddField(
            model_name='apihead',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='AutoInterface.ApiInfo', verbose_name='所属接口'),
        ),
    ]
