# Generated by Django 2.1.7 on 2021-04-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoStress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stress',
            name='single',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='single'),
        ),
    ]
