# Generated by Django 2.1.7 on 2021-02-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auto_uicase',
            fields=[
                ('caseid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='名称')),
                ('testdata', models.CharField(blank=True, max_length=100, null=True, verbose_name='关联测试数据')),
                ('type', models.CharField(blank=True, max_length=10, null=True, verbose_name='类型')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'auto_uicase',
                'verbose_name_plural': 'auto_uicase',
                'db_table': 'auto_uicase',
            },
        ),
        migrations.CreateModel(
            name='auto_uirecord',
            fields=[
                ('recordid', models.AutoField(primary_key=True, serialize=False)),
                ('studyuid', models.CharField(blank=True, max_length=200, null=True, verbose_name='studyuid')),
                ('vote', models.TextField(blank=True, max_length=800, null=True, verbose_name='挂载')),
                ('expect', models.CharField(blank=True, max_length=30, null=True, verbose_name='预期结果')),
                ('actual', models.CharField(blank=True, max_length=30, null=True, verbose_name='实际结果')),
                ('aistatus', models.CharField(blank=True, max_length=5, null=True, verbose_name='预测结果')),
                ('starttime', models.CharField(blank=True, max_length=20, null=True, verbose_name='开始时间')),
                ('completiontime', models.CharField(blank=True, max_length=20, null=True, verbose_name='结束时间')),
                ('result', models.TextField(blank=True, max_length=2500, null=True, verbose_name='结论')),
                ('type', models.TextField(blank=True, max_length=10, null=True, verbose_name='类型')),
                ('server', models.TextField(blank=True, max_length=20, null=True, verbose_name='服务')),
                ('caseid', models.IntegerField(default=False, verbose_name='caseid')),
                ('autoid', models.IntegerField(default=False, verbose_name='autoid')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'auto_uirecord',
                'verbose_name_plural': 'auto_uirecord',
                'db_table': 'auto_uirecord',
            },
        ),
        migrations.CreateModel(
            name='autoui',
            fields=[
                ('autoid', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, max_length=20, null=True, verbose_name='版本')),
                ('setup', models.CharField(blank=True, max_length=20, null=True, verbose_name='setup用例')),
                ('cases', models.CharField(blank=True, max_length=20, null=True, verbose_name='用例')),
                ('tearDown', models.CharField(blank=True, max_length=20, null=True, verbose_name='tearDown用例')),
                ('progress', models.CharField(blank=True, max_length=5, null=True, verbose_name='进度')),
                ('thread', models.CharField(blank=True, max_length=5, null=True, verbose_name='线程数')),
                ('starttime', models.CharField(blank=True, max_length=20, null=True, verbose_name='开始预测时间')),
                ('completiontime', models.CharField(blank=True, max_length=20, null=True, verbose_name='结束预测时间')),
                ('total', models.CharField(blank=True, max_length=5, null=True, verbose_name='count')),
                ('hostid', models.IntegerField(default=False, verbose_name='hostid')),
                ('report', models.CharField(blank=True, max_length=80, null=True, verbose_name='报告')),
                ('type', models.CharField(blank=True, max_length=10, null=True, verbose_name='类型')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
            ],
            options={
                'verbose_name': 'autoui测试表',
                'verbose_name_plural': 'autoui测试表',
                'db_table': 'autoui',
            },
        ),
    ]
