# Generated by Django 2.1.7 on 2021-02-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoUI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_uirecord',
            name='dicomid',
            field=models.IntegerField(default=False, verbose_name='dicomid'),
        ),
        migrations.AlterField(
            model_name='auto_uirecord',
            name='server',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='服务'),
        ),
        migrations.AlterField(
            model_name='auto_uirecord',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='类型'),
        ),
    ]
