# Generated by Django 2.1.7 on 2021-03-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='errorlog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, max_length=10, null=True, verbose_name='版本')),
                ('content', models.TextField(blank=True, max_length=2000, null=True, verbose_name='错误内容')),
                ('route', models.TextField(blank=True, max_length=500, null=True, verbose_name='路径')),
                ('stressid', models.IntegerField(blank=True, null=True, verbose_name='stressID')),
            ],
            options={
                'verbose_name': '压测错误日志记录表',
                'verbose_name_plural': '压测错误日志记录表',
                'db_table': 'errorlog',
            },
        ),
    ]
